controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    otto_position_controller:
      type: position_controllers/JointGroupPositionController

otto_position_controller:
  ros__parameters:
    joints:
      - leg_right_joint
      - leg_left_joint
      - foot_right_joint
      - foot_left_joint
